### ISSUE TITLE
Problem during installation 

### ISSUE THREAD

**Issue by loguille** [cdebodt/Fast_Multi-scale_NE#6]
Hello, 
I would be interested to use fmsne package in python, but I get an error during installation.  
when I run : 
`pip install .`  
I get the error :
``` 
Processing /Fast_Multi-scale_NE
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [93 lines of output]
      performance hint: fmsne/fmsne_implem.pyx:590:5: Exception check on 'sne_hdpinn_nolog' will always require the GIL to be acquired.
      Possible solutions:
          1. Declare 'sne_hdpinn_nolog' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
          2. Use an 'int' return type on 'sne_hdpinn_nolog' to allow an error code to be returned.
      performance hint: fmsne/fmsne_implem.pyx:743:5: Exception check on 'ms_ldprec_nofitU' will always require the GIL to be acquired.
      Possible solutions:
          1. Declare 'ms_ldprec_nofitU' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
          2. Use an 'int' return type on 'ms_ldprec_nofitU' to allow an error code to be returned.
      performance hint: fmsne/fmsne_implem.pyx:766:5: Exception check on 'ms_ldprec' will always require the GIL to be acquired.
      Possible solutions:
          1. Declare 'ms_ldprec' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
          2. Use an 'int' return type on 'ms_ldprec' to allow an error code to be returned.
      performance hint: fmsne/fmsne_implem.pyx:1167:5: Exception check on 'mstsne_symmetrize' will always require the GIL to be acquired.
      Possible solutions:
          1. Declare 'mstsne_symmetrize' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
          2. Use an 'int' return type on 'mstsne_symmetrize' to allow an error code to be returned.
      performance hint: fmsne/fmsne_implem.pyx:2431:5: Exception check on 'f_ldprec' will always require the GIL to be acquired.
      Possible solutions:
          1. Declare 'f_ldprec' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
          2. Use an 'int' return type on 'f_ldprec' to allow an error code to be returned.
      performance hint: fmsne/fmsne_implem.pyx:3452:5: Exception check on 'fmstsne_symmetrize' will always require the GIL to be acquired.
      Possible solutions:
          1. Declare 'fmstsne_symmetrize' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
          2. Use an 'int' return type on 'fmstsne_symmetrize' to allow an error code to be returned.```
```   
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              popt.ns = k
              popt.inv_ns = Nd
              popt.p_h = &p_h[h]
              popt.t_h = &t_h[h]
              # Performing the optimization
              lbfgs(prod_N_nc, xopt, NULL, mssne_evaluate, NULL, popt, pparam)
                                           ^
      ------------------------------------------------------------
      
      fmsne/fmsne_implem.pyx:1146:37: Cannot assign type 'lbfgsfloatval_t (void *, const lbfgsfloatval_t *, lbfgsfloatval_t *, const int, const lbfgsfloatval_t) except? -1 nogil' to 'lbfgs_evaluate_t' (alias of 'lbfgsfloatval_t (*)(void *, lbfgsconst_p, lbfgsfloatval_t *, int, lbfgsfloatval_t) noexcept'). Exception values are incompatible. Suggest adding 'noexcept' to the type of 'mssne_evaluate'.
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              # Updates related to the current multi-scale optimization step
              ms_update_mso_step(k, h, N, K_star, ds_hd, tau_h, simhd_ms, simhd_h)
              # Symmetrizing the multi-scale HD similarities in simhd_h. Be careful that only the top half of simhd_h contains the symmetric HD similarities.
              mstsne_symmetrize(K_star, simhd_ms, simhd_h)
              # Performing the optimization
              lbfgs(prod_N_nc, xopt, NULL, mstsne_evaluate, NULL, popt, pparam)
                                           ^
      ------------------------------------------------------------
      
      fmsne/fmsne_implem.pyx:1391:37: Cannot assign type 'lbfgsfloatval_t (void *, const lbfgsfloatval_t *, lbfgsfloatval_t *, const int, const lbfgsfloatval_t) except? -1 nogil' to 'lbfgs_evaluate_t' (alias of 'lbfgsfloatval_t (*)(void *, lbfgsconst_p, lbfgsfloatval_t *, int, lbfgsfloatval_t) noexcept'). Exception values are incompatible. Suggest adding 'noexcept' to the type of 'mstsne_evaluate'.
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              else:
                  popt.p_h = &p_h[h]
                  popt.t_h = &t_h[h]
              popt.sbsa += K_star
              # Performing the optimization
              lbfgs(prod_N_nc, xopt, NULL, fmssne_evaluate, NULL, popt, pparam)
                                           ^
      ------------------------------------------------------------
      
      fmsne/fmsne_implem.pyx:3298:37: Cannot assign type 'lbfgsfloatval_t (void *, const lbfgsfloatval_t *, lbfgsfloatval_t *, const int, const lbfgsfloatval_t) except? -1' to 'lbfgs_evaluate_t' (alias of 'lbfgsfloatval_t (*)(void *, lbfgsconst_p, lbfgsfloatval_t *, int, lbfgsfloatval_t) noexcept'). Exception values are incompatible. Suggest adding 'noexcept' to the type of 'fmssne_evaluate'.
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              # that only the similarities between i and j such that j>i are
              # actually symetrized, since only these are used in the
              # evaluate function.
              fmstsne_symmetrize(n_rs, sLm_nt, simhd_ms_nn_i_rs, m_nn, simhd_h_nn_i_rs)
              # Performing the optimization
              lbfgs(prod_N_nc, xopt, NULL, fmstsne_evaluate, NULL, popt, pparam)
                                           ^
      ------------------------------------------------------------
      
      fmsne/fmsne_implem.pyx:3956:37: Cannot assign type 'lbfgsfloatval_t (void *, const lbfgsfloatval_t *, lbfgsfloatval_t *, const int, const lbfgsfloatval_t) except? -1' to 'lbfgs_evaluate_t' (alias of 'lbfgsfloatval_t (*)(void *, lbfgsconst_p, lbfgsfloatval_t *, int, lbfgsfloatval_t) noexcept'). Exception values are incompatible. Suggest adding 'noexcept' to the type of 'fmstsne_evaluate'.
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/Fast_Multi-scale_NE/setup.py", line 21, in <module>
          ext_modules = cythonize([
                        ^^^^^^^^^^^
        File "/home/miniconda3/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
          cythonize_one(*args)
        File "/home/miniconda3/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: fmsne/fmsne_implem.pyx
      Compiling fmsne/fmsne_implem.pyx because it changed.
      [1/1] Cythonizing fmsne/fmsne_implem.pyx
      [end of output]
 
```  
note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details. 
```

Thanks in advance for the reply.

Loïc Guille

**Comment by lgatto** [comment]
Looking at 

```
fmsne/fmsne_implem.pyx:1146:37: Cannot assign type 'lbfgsfloatval_t 
````

I do remember having issues initially with the [`lbfgs` dependency](https://github.com/cdebodt/Fast_Multi-scale_NE/issues/2).

Could you try to clone the repo and install locally with `pip install .`.

**Comment by loguille** [comment]
I tried to clone the repo and install localy but I'm running the same error.

**Comment by loguille** [comment]
So in order to install it, I finally downgrade Cython from version 3.0.10 to 0.29.35 using :
`pip install Cython==0.29.35`
 and then install pylbfgs : 
`pip install pylbfgs`
and it works now

Thank you for the help
